# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.fpop <- function(data, penalty, min_mean, max_mean, cost_mat_r, end_vec_r, mean_vec_r, intervals_mat_r) {
    .Call(`_ChangepointInference_fpop_interface2`, data, penalty, min_mean, max_mean, cost_mat_r, end_vec_r, mean_vec_r, intervals_mat_r)
}

.k_step_bs <- function(y, n_steps) {
    .Call(`_ChangepointInference_k_step_bs_r`, y, n_steps)
}

.fpop_inference <- function(data, penalty, window_size, sig, return_dev = 0L) {
    .Call(`_ChangepointInference_fpop_inference_interface_recycle`, data, penalty, window_size, sig, return_dev)
}

.k_step_bs_inference <- function(y, n_steps, type, sigma, window_size = 0L, approximation_threshold = 5, return_dev = 0L) {
    .Call(`_ChangepointInference_k_step_bs_inference_r`, y, n_steps, type, sigma, window_size, approximation_threshold, return_dev)
}

